name: Release Pipeline

on:
    push:
      branches:
        - '**'
    pull_request:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer, phpunit
        extensions: simplexml

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: "Install JS dependencies"
      run: npm install

    - name: Build Javascript
      run: npm run build

    - name: Install Composer dependencies
      run: composer install --no-dev

    - name: Manipulations for WordPress Plugin Release
      run: sed -i 's/echo \$err;/echo esc_html(\$err);/' build/lib/autoload.php

    - name: Copy files for plugin-release directory
      run: |
        mkdir -p plugin-release
        cp -R build/* plugin-release/

    - name: Parse Stable Tag from readme.txt
      id: get_version
      run: |
        version=$(grep -Po '(?<=Stable tag: ).*' release-plugin-directory/trunk/readme.txt | xargs)
        echo "stable_version=$version" >> $GITHUB_ENV

    - name: Generate release zip-file
      run: |
        npm run plugin-zip 
        mkdir release
        zip_name="sams-integration-${{ env.stable_version }}.zip"
        mv sams-integration.zip release/$zip_name
        echo "zip_name=$zip_name" >> $GITHUB_ENV

    - name: Upload Pipeline Release
      uses: actions/upload-artifact@v4
      with:
        name: SAMS Integration ${{ env.stable_version }}
        path: release/${{ env.zip_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@master


    - name: Prepare release folder
      env:
        BUILD_DIR: "build"
        RELEASE_TRUNK_DIR: "release-plugin-directory/trunk"
      run: |
        cp -r "$BUILD_DIR" "$RELEASE_TRUNK_DIR"
        cp sams-integration.php "$RELEASE_TRUNK_DIR"
        echo "Copied files to release trunk"

    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_COMPRESS: zip
        GHR_PATH: release-plugin-directory/trunk
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
