name: Pipeline release

on:
    push:
      branches:
        - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer, phpunit
        extensions: simplexml

    - name: Install Composer dependencies
      run: composer install

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: "Install JS dependencies"
      run: npm install

    - name: Build Javascript
      run: npm run build

    - name: Archive Pipeline Build
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: release-${{ github.run_id }}.zip
        exclusions: '*.git* /*node_modules/* .editorconfig phpunit.xml.dist composer.json composer.lock .wp-env.json /src/* /tests/*'
    
    - name: Upload Pipeline Release
      uses: actions/upload-artifact@v4
      with:
        name: Release ${{ github.run_id }} (SAMS Plugin)
        path: release-${{ github.run_id }}.zip