name: Pipeline release

on:
    push:
      branches:
        - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer, phpunit
        extensions: simplexml

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: "Install JS dependencies"
      run: npm install

    - name: Build Javascript
      run: npm run build
    
      # Needs to run _after_ JS build - JS build copies php files to the build-directory
    - name: Install Composer dependencies
      run: composer install --no-dev

    #- name: Manipulations for WordPress Plugin Release
    # 1. Replace generated echos by escaped output
    #  run: sed -i 's/echo \$err;/echo esc_html(\$err);/' build/lib/autoload.php

    - name: Generate release zip-file
      run: |
        npm run plugin-zip 
        mkdir release
        mv sams-integration.zip release/sams-integration-${{ github.run_id }}-snapshot.zip

    - name: Upload Pipeline Release
      uses: actions/upload-artifact@v4
      with:
        name: SAMS Integration ${{ github.run_id }}
        path: release/sams-integration-${{ github.run_id }}-snapshot.zip
