name: Build, Test and Release WordPress Plugin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer, phpunit

      - name: Install Composer dependencies
        run: composer install

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install wp-env
        run: npm install --global @wordpress/env

      - name: Start wp-env
        run: wp-env start

      - name: Run PHPUnit tests
        run: wp-env run tests 'vendor/bin/phpunit'

      - name: Stop wp-env
        run: wp-env stop
#
  #release:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  if: github.event_name == 'release'
#
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4
#
  #    - name: Set up PHP
  #      uses: shivammathur/setup-php@v2
  #      with:
  #        php-version: '8.3'
#
  #    - name: Install Composer dependencies
  #      run: composer install --no-dev --prefer-dist --no-progress --no-suggest
#
  #    - name: Create a zip file of the plugin
  #      run: zip -r sams-plugin.zip . -x "*.git*" "tests/*" "vendor/*"
#
  #    - name: Upload Release Asset
  #      uses: actions/upload-release-asset@v1
  #      with:
  #        name: sams-plugin.zip
  #        path: sams-plugin.zip
  #        label: "Sams Plugin"
#